- role: Workshop Organizer
  description: "[3rd KAIST-Mila Prefrontal AI Workshop](https://sites.google.com/view/kaist-mila-ai-workshop-3rd/) (6 invited speakers incl. [Y. Bengio](https://yoshuabengio.org/)), [2nd KAIST-Mila Prefrontal AI Workshop](https://sites.google.com/view/kaist-mila-ai-workshop-2nd) (6 invited speakers incl. [Y. Bengio](https://yoshuabengio.org/))"
- role: Reviewer
  description: "[ICLR 2025-2026](https://iclr.cc/), [ICML 2026](https://icml.cc/) 🥈 Silver Reviewer, [NeurIPS 2026](https://neurips.cc/), [TMLR 2026–](https://jmlr.org/tmlr/)"
